// <auto-generated />
namespace PRS_Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedPurchaseRequestmodelwithnewproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedPurchaseRequestmodelwithnewproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281542462_updated PurchaseRequest model with new properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
