// <auto-generated />
namespace PRS_Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdatedPurchaseRequestLineItemsmodelwithnewpropertiesandattributeupdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatedPurchaseRequestLineItemsmodelwithnewpropertiesandattributeupdates));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281546359_Updated PurchaseRequestLineItems model with new properties and attribute updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
